export let projects = [
{
  'Name': `GoodGames Trivia App`,
  'Build': `React, Node, Express, Jest, RTL`,
    'Description': `For this project, a user can answer random questions fetched from the Open Trivia Database in a space-themed UI.`,
  'Image': `./images/question-ss.png`,
  'Link': `https://github.com/m3ia/quiz-app`,
  'Project Type': `#PracticeMakesProgress`,
},
  {
  'Name': `React Memory Game`,
  'Build': `React, HTML, CSS`,
    'Description': `After taking 1 week to review some React basics, I built a React-based memory game to apply my understanding. This game uses a set of imported images, which a user can click and match based on memory.`,
  'Image': `./images/memory-game.png`,
  'Link': `https://github.com/m3ia/memory-game`,
  'Project Type': `#PracticeMakesProgress`,
},
  {
  'Name': `Sudoku Puzzle`,
  'Build': `JS, HTML, CSS`,
  'Description': `For Techtonica, I spent ~4 days building a game I'm passionate about: Sudoku. My favorite part building this game was figuring out an algorithm to dynamically update the styling according to duplicates in a row, column, and a parent box grid.`,
  'Image': `./images/sudoku.png`,
  'Link': `https://github.com/m3ia/sudoku_v2`,
  'Project Type': `Passion Project`,
},
  {
  'Name': `Mock Recipe Blog Page`,
  'Build': `JS, HTML, CSS`,
  'Description': `For this project, I practiced designing a complete recipe page. I really enjoyed working on this project to deepen my knowledge of CSS. (Also because I featured a recipe for one of my favorite snacks.)`,
  'Image': `./images/mock-recipe.png`,
  'Link': `https://github.com/m3ia/mock-recipe-page/blob/main/README.md`,
  'Project Type': `Passion Project`,
},
{
  'Name': `Got It!`,
  'Build': `Node.js, React.js, Express.js, Postgres, Google Cal API, Google, OAuth2, Bootstrap`,
  'Description': `Got It! is a shopping list app for anyone who loves to cook, prep, and plan on a regular basis. \n Got It has a recurring list feature where you can stay on top of your recurring shopping lists on a regular basis.`,
  'Image': `./images/got-it.png`,
  'Link': `https://github.com/m3ia/GotIt`,
  'Project Type': `Passion Project`,
},

{
  'Name': `Guess That Number!`,
  'Build': `HTML, CSS, and Bootstrap`,
  'Description': `With this game, one can practice binary search. Built to be accessible to those with visual or physical impairments and/or dyslexia.`,
  'Image': `./images/guess-that-num.png`,
  'Link': `https://github.com/m3ia/m3ia.github.io/blob/main/README.md`,
  'Project Type': `Passion Project`,
  },
{
  'Name': `Bank Account Page`,
  'Build': `HTML, CSS, JavaScript`,
  'Description': `Practiced DOM manipulation by creating a mock-up bank account for a fake user named "Billy". All of the HTML was done via JS scripts.`,
  'Image': `./images/bank-acct-img.png`,
  'Link': `https://github.com/m3ia/bank-account-practice`,
  'Project Type': `#PracticeMakesProgress`,
},
{
  'Name': `Listings Practice`,
  'Build': `React, Tailwind CSS`,
  'Description': `I used this project to practice dynamically updating a view of mock-up property listings according to 3 ways of searching: \n typing a property name in the search bar, \n selecting/deselecting amenities, \n and filtering by occupancy range.`,
  'Image': `./images/listings-practice.png`,
  'Link': `https://github.com/m3ia/listings-practice`,
  'Project Type': `#PracticeMakesProgress`,
},

];